#############################################################################################  
############################## DataSource properties ########################################  
#############################################################################################  
spring:  
  datasource:  
#    schema : classpath:init-sql/schema.sql  
#    data: classpath:init-sql/data.sql  
    continue-on-error : true  
    name: master  
    driver-class-name: oracle.jdbc.OracleDriver  
    type: com.alibaba.druid.pool.DruidDataSource  
    url : jdbc:oracle:thin:@192.168.2.97:1521:orcl  
    username: wfwkns  
    password: wfwkns  
    filters: stat  
    maxActive: 20  
    initialSize: 1  
    maxWait: 60000  
    minIdle: 1  
    timeBetweenEvictionRunsMillis: 60000  
    minEvictableIdleTimeMillis: 300000  
    validationQuery: select 'x' from dual  
    testWhileIdle: true  
    testOnBorrow: false  
    testOnReturn: false  
    poolPreparedStatements: true  
    maxOpenPreparedStatements: 20  
  mvc:  
    view:  
      prefix: /WEB-INF/jsp/  
      suffix: .jsp  
  jackson:  
    date-format: yyyy-MM-dd HH:mm:ss  
    time-zone: GMT+8  
##########################################################################################################  
###########################################spring boot redis #############################################  
##########################################################################################################  
  redis:  
    database: 0           # Redis数据库索引（默认为0）  
    host: 192.168.35.118   # Redis服务器地址  
    port: 16379            # Redis服务器连接端口  
    password: 37621040     #Redis服务器连接密码（默认为空）  
    timeout: 0            # 连接超时时间（毫秒）  
    pool:  
      max-idle: 8         # 连接池中的最大空闲连接  
      min-idle: 1         # 连接池中的最小空闲连接  
      max-active: 8       # 连接池最大连接数（使用负值表示没有限制）  
      max-wait: -1        # 连接池最大阻塞等待时间（使用负值表示没有限制）  
#    sentinel:  
#      master:  
#      nodes:  
####################################################################################  
###################################MyBatis Plus Config##############################  
####################################################################################  
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  typeAliasesPackage: com.ly.cloud.entity
#  typeEnumsPackage: com.ly.cloud.domain.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 0
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: 1
    logic-not-delete-value: 0
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.mybatisplus.mapper.MetaObjectHandler
    #自定义SQL注入器 逻辑删除SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false 
############################################################################################
 ######################################## feign 配置 ##########################################
 ############################################################################################
feign:
  hystrix:
    enabled: true
ribbon:  
  ReadTimeout: 60000  
  ConnectTimeout: 60000
hystrix: 
  command: 
    default:  
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 60000
 #############################################################################################
 ######################################### flyway 配置 #########################################
 #############################################################################################
flyway:
  baselineOnMigrate: true
  locations: db/migration
  table: VERSION_SM_DIFFICULT_STUDENT